[package]
name = "xplm-sys"
version = "0.1.1"
edition = "2021"
authors = ["David Dunwoody <david.dunwoody@gmail.com>"]

[features]
generate-bindings = ["dep:bindgen"]

[build-dependencies]
bindgen = { version = "0.69.4", optional = true }
