[package]
name = "xplm-sys"
version = "0.1.0"
edition = "2021"
authors = ["David Dunwoody <david@flightlevelchange.co.uk>"]

[features]
generate-bindings = ["dep:bindgen"]

[build-dependencies]
bindgen = { version = "0.65.1", optional = true }
